### ISSUE TITLE
Caption text not shown until video is played?

### ISSUE THREAD

**Issue by oldrup** [highrisedigital/better-core-video-embeds#2]
In the block editor, it's possible to add a caption (figcaption I suppose) to the YouTube block.

On the front end, it appears that the caption is not shown, unless the video is played.

Something you can reproduce?

![image](https://user-images.githubusercontent.com/17141205/204338378-5fbf799f-228e-46c1-b93a-7ac8ea244d68.png)

**Comment by wpmark** [comment]
@oldrup this is a great idea and it will be in the next release out shortly.

**Comment by wpmark** [comment]
This is now included in the recent version 1.1 release.
